services:
  ardupilot-sil:
    build:
      context: .
      dockerfile: ardupilot-sil.Dockerfile

    container_name: ardupilot-sil
    ports:
    - 15760-16000:5760-6000
    restart: 'always'
    environment:
    - COUNT=${NUMCOPTERS:-3}
    
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    command: redis-server --save 60 1 --loglevel warning

volumes:
  redis-data:
    driver: local