services:
  ardupilot-sil:
    build:
      context: .
      dockerfile: ardupilot-sil.Dockerfile

    container_name: ardupilot-sil
    network_mode: host
    restart: 'always'
    environment:
    - COUNT=${NUMCOPTERS:-3}
    
  redis:
    image: redis:latest
    container_name: redis
    network_mode: host
    volumes:
      - redis-data:/data
    restart: always
    command: redis-server --save 60 1 --loglevel warning

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    network_mode: host
    volumes:
      - redisinsight-data:/data
    restart: always

volumes:
  redis-data:
    driver: local
  redisinsight-data:
    driver: local